### ISSUE TITLE
A simple example

### ISSUE THREAD

**Issue by foo123** [R3VoLuT1OneR/doctrine-rest#1]
Hello I want to use the project doctrine-rest for a small test that I have. I want it because I want to use doctrine as ORM as well. I have a specification to use HTTP JSON API for subscribers and fields (each subscriber can have multiple fields). Can you provide a simple working example on how to use it or maybe you have wiki? Where is the documentation page?
All I want is a base example with routing added and how to handle incoming requests. Is routing supported in doctrine-rest or is an external class (maybe symfony?)?

Thanks in advance,
Nikos

**Comment by R3VoLuT1OneR** [comment]
Hey

Only documentation exists right now is in README file.
Routing is not supported should be implemented depend on framework used.
The best way to get into the library is to read unit tests.
https://github.com/R3VoLuT1OneR/doctrine-rest/tree/master/tests/unit/Action

Currently implemented integration with Laravel framework:
https://github.com/R3VoLuT1OneR/laravel-doctrine-rest
But also there is no usage examples.

**Comment by foo123** [comment]
Ok I will read those links and try to get an understanding. Please keep this open for a while.
May I ask what a EntityTransformer is and how to use? Also where should I implement JsonApiResource on doctrine entity and what should this do?

Thanks so far

**Comment by foo123** [comment]
Can I hire you to develop a small json api test case for subscribers and fields using some rest php library out of the box with doctrine? I already have the models and all of that but I am afraid I will run out of time (I have 8 days to deliver it) if I try to delve into and extract the documentation. This way I can learn by example while at the same time I develop the test case. If you are interested let me know.

**Comment by R3VoLuT1OneR** [comment]
`EntityTransformer` is a fractal transformer. I use fractal library for transformation entities into JSON API response. https://fractal.thephpleague.com/

`JsonApiResource` should be implemented on doctrine entity in order to build proper references url in JSON API response.

Basically the library is collection of REST actions. So depend on REST action you need, you should look how each action implemented.

So the action flow next:

1. Get symfony httpfoundation request and create new `RestRequest` object.
```php
// Get http request from framework or init yourself
$httpRequest = Symfony\Component\HttpFoundation\Request::createFromGlobals();
$restRequest = new RestRequest($httpRequest);
```
Or implement your own request class that will implement `RestRequestContract`

2. After you have request we need create an `CollectionAction` object, that used for Index rest actions. For that we would net `RestRepository` object, that used as `EntityRepository` for rest actions and fractal transformer.
 ```
$transformer = new SubscriberTransformer();

$restRepository = new RestRepository(
    $entityManager,
    $entityManager->getClassMetadata(Subscriber::class)
);

$action = new CollectionAction($restRepository, $transformer);

// dispatch action
$response = $action->dispatch($request);
```

3. `$response` is `RestResponse` object, that extends `Symfony\Component\HttpFoundation\JsonResponse` that easily converts into json response.

**Comment by R3VoLuT1OneR** [comment]
@foo123 Sent you hangout invite to `nikosms0` at gmail. you can add me `r3volut1oner`

**Comment by foo123** [comment]
can we do skype? I can send you the requirements..

**Comment by R3VoLuT1OneR** [comment]
@foo123 Find me in skype, same username

**Comment by foo123** [comment]
Ok i did, waiting for response.

**Comment by foo123** [comment]
Thank you for your skype response. I will try to work it out and see how it goes. If I have further questions/issues I will post on github. Thanks

**Comment by foo123** [comment]
Can you provide an example flow with ItemAction? The resource id is passed as parameter to the controller. Thsi is what I have right now:

```php
	/**
	* @Route("/api/subscriber/{id}", requirements={"id"="\d+"}, methods={"GET"})
	*/
	public function showAction(Request $httpRequest, $id)
    {
		$restRequest = new RestRequest($httpRequest);
		$transformer = new SubscriberTransformer();
		$entityManager = $this->getDoctrine()->getManager();
		
		$restRepository = new RestRepository(
		   $entityManager,
		   $entityManager->getClassMetadata(Subscriber::class)
		);
		$action = new ItemAction($restRepository, $transformer);
        
		// dispatch action
		$restResponse = $action->dispatch($restRequest);
		return $restResponse;
    }
````

Does this work? How is `id` parameter passed to ItemAction, will it take it from request somehow, do I need to pass it along? The laravel controller you have as example does not show how this is handled.

Thanks
