### ISSUE TITLE
Custom urls??

### ISSUE THREAD

**Issue by foo123** [R3VoLuT1OneR/doctrine-rest#3]
Hello Pavel, is there an option for custom urls? My routes are prefixed with /api/ for all resources.
Eg instead of /subscribers, /fields I have /api/subscribers, /api/fields. As I understand the urls are generated automaticaly from the jsonresourcekey parameter, however can I have my custom urls without changing jsonresourcekey or any other way? I would prefer to have the /api/ prefix, else I can default to without prefix.

Thank you,
Nikos

**Comment by R3VoLuT1OneR** [comment]
@foo123 You should extend and override `RestRequest::getBaseUrl()` method.

**Comment by foo123** [comment]
Ok wil see that. Thanks Pavel.

**Comment by foo123** [comment]
Works fine with extending `RestRequest` class and changing `getBaseUrl` method to include `/api` prefix. Closing this
