### ISSUE TITLE
CreateAction relationships

### ISSUE THREAD

**Issue by foo123** [R3VoLuT1OneR/doctrine-rest#4]
I have a test project with subscribers which have many fields (relationship). I want in CreateAction for a subscriber to post the (new) fields as well and create thise and assign to subscriber. Is this possible with Doctrine/Rest CreateAction?

In test cases there is an example of create_user_and_blog where the associated role of a user is posted along with the new user data. But the roles already exists (it even has an id). Can this be done for collection fields without having them be pre-created?

FYI the doctrine models are already setup with manytoone and onetomany relationships (each Field entity has an associated Subscriber with associated `subscriber_id` in DB which points to the subscriber) with getters and setters. Also each subscriber has an `addField` public method to add fields.

Thanks,
Nikos

**Comment by R3VoLuT1OneR** [comment]
@foo123 You can send data within `relationships` field. When creating new subscriber.
Configure cascade `persist` for fields property in subscriber property and it should work.

**Comment by foo123** [comment]
Btw the way do you have any php test client that posts requests to server? I will need this to test the api. 
Something like an HTTP Client that supports the JSON API specification. Is there anything in php?

**Comment by R3VoLuT1OneR** [comment]
@foo123 Add `cascade={"merge","persist","refresh","remove"}` to `@ORM\OneToMany()`.
I don't know any php client for it. I would test it with phpunit.

**Comment by foo123** [comment]
Pavel, are you sure this will work? Do I need to change the `Subscriber::addField` or `Field::setSubscriber` methods? `Doctrine/Rest` will take care?

PS: About http client I am thinking use one in node for http requests where I set the body and accept header manually to create/list/update resources. I am on to that right now

**Comment by foo123** [comment]
I want to construct a json for creating new subscriber with additional fields. Subscirber has these attributes (except `id`):

```text
[name, email, state]
````

and additional fields have these attributes (except `id`)

```text
[title, type]
```

Will the following json work (state is optional)?

```json
{
	"data": {
		"type": "subscriber",
		"attributes": {
			"name" : "subscriber3",
			"email": "s3@gmail.com",
			"state": "unconfirmed"
		}
	},
	"included": [
		{
			"type": "field",
			"attributes": {
				"title": "name",
				"type": "string"
			}
		},
		{
			"type": "field",
			"attributes": {
				"title": "price",
				"type": "number"
			}
		}
	]
}
```

**Comment by R3VoLuT1OneR** [comment]
@foo123 Please see JSON API create resource documentation at http://jsonapi.org/format/#crud-creating.

In the next example data format in JSON that should be sent in order to create subscriber with fields.
To implement it you need get `setFields($fields)` on `Subscriber` entity, `$fields` will be array of `Field` entities.

```
{
	"data": {
		"type": "subscriber",
		"attributes": {
			"name" : "subscriber3",
			"email": "s3@gmail.com",
			"state": "unconfirmed"
		},
		"relationships": {
                        "fields": {
                                "data": [
					{
						"attributes": {
							"title": "name",
							"type": "string"
						}
					},
					{
						"attributes": {
							"title": "price",
							"type": "number"
						}
					}
				]
			}
		}
	}
}
```

**Comment by foo123** [comment]
I get follwoing error when I posted above json:

```text
{
  "errors": [{
    "code": "missing-root-data",
    "source": {
      "pointer": ""
    },
    "detail": "Missing `data` member at document top level."
  }]
}
```

**Comment by foo123** [comment]
It doesnt work even when trying simply to create a new subscriber without fields like following:

```text
{
	"data": {
		"type": "subscriber",
		"attributes": {
			"name" : "new subscriber",
			"email": "a_sub@gmail.com",
			"state": "unconfirmed"
		}
}
```

it returns an error:

```text
422 Unprocessable Entity
{
  "errors": [{
    "code": "missing-root-data",
    "source": {
      "pointer": ""
    },
    "detail": "Missing `data` member at document top level."
  }]
}```

What can go wrong here?

**Comment by foo123** [comment]
I think sth is happening with this method of `RestRequest`

```php
    /**
     * @return array
     * @throws RestException
     */
    public function getData()
    {
        $request = $this->http()->request;

        if ($request->has('data')) {
            return $request->get('data');
        }

        throw RestException::missingRootData();
    }

```

How to post data? Do I need only the json or do I need a url-encoded form eg:

This:
```text
{"data":{"type":"subscriber","attributes":{"name":"new subscriber","email":"a_sub@gmail.com","state":"unconfirmed"}
}}
```

Or this:
```text
data=%7B%22data%22%3A%7B%22type%22%3A%22subscriber%22%2C%22attributes%22%3A%7B%22name%22%3A%22new%20subscriber%22%2C%22email%22%3A%22a_sub%40gmail.com%22%2C%22state%22%3A%22unconfirmed%22%7D%0A%7D%7D
```

**Comment by foo123** [comment]
I managed to make it work by overriding the RestRequest getData method like the follwoing:

```php
	/**
     * @return array
     * @throws RestException
     */
    public function getData()
    {
        $request = $this->http()->request;

        if ($request->has('data')) {
            return $request->get('data');
        }
		
		$payload = $this->http()->getContent();
		$data = json_decode($payload, true);
		if (is_array($data) && isset($data['data'])) {
			return $data['data'];
		}

        throw RestException::missingRootData();
    }

```

Is this good solution?

**Comment by foo123** [comment]
When I try to create subscriber with associated fields (create the fields as well) per your json example above I get following internal error:

```text
An exception occurred while executing \'INSERT INTO field (title, type, subscriber_id) VALUES (?, ?, ?)\' with params [\"name\", \"string\", null]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column \'subscriber_id\' cannot be null
```

subscriber_id in table of fields is inserted as null, what can I do with that? Enable it to be non null? Is this temporary? Will it save the id in another transaction? Thanks

**Comment by R3VoLuT1OneR** [comment]
@foo123 RestRequest data accepts form data not JSON, you properly override the `getData()` method for achieving that. You get error because there is no `Subscriber` entity set on `Field`. You can send `subscriber_id` with request or set it inside `setFields()` it will be good to do it inside the `setFields()` with loop do `$field->setSubscriber($this);`.

**Comment by R3VoLuT1OneR** [comment]
@foo123 Data should be sent for `form/url-encoded` as you showed in previous example:
```
data=%7B%22data%22%3A%7B%22type%22%3A%22subscriber%22%2C%22attributes%22%3A%7B%22name%22%3A%22new%20subscriber%22%2C%22email%22%3A%22a_sub%40gmail.com%22%2C%22state%22%3A%22unconfirmed%22%7D%0A%7D%7D
```

**Comment by foo123** [comment]
This issue is resolved. But I still do not know how to send data using your format. Please post a simplest example of data (using your method of `$http->request`, not `json`) to send to request body so I can test it. Then closing this.

**Comment by R3VoLuT1OneR** [comment]
@foo123 I don't understand what is your problem here.
Just send regular form data to `POST /subscriber`:
```
data[type]=subscriber&
data[attributes][name]=new_subscriber&
data[attributes][email]=fsadfas@fadsfa.com
```
It is not accept json by default, yeah. It is should be fixed on implementation side for now.

**Comment by foo123** [comment]
@R3VoLuT1OneR  Nevermind I fixed this. I just had to add the header `Content-type: application/x-www-form-urlencoded` and it worked like a charm. Good work. Closing this
