### ISSUE TITLE
return resource objects vs resource linkage objects??

### ISSUE THREAD

**Issue by foo123** [R3VoLuT1OneR/doctrine-rest#7]
According to the json-api specification a url like `resource1/{id}/resource2` should return the resource objetcs (with attributes, relationships and so on), while the url `resource1/{id}/relationships/resource2` should return ONLY the resource linkage objects (meaning just `type` and `id`) how to control what to return in doctrine-rest? (`resource1` is the primary resource, while `resource2` is the secondary resource, eg onetoone or onetomany relations). is a custom transformer needed or a tweeking in the lib? Please advise.

Thanks,
Nikos

**Comment by R3VoLuT1OneR** [comment]
@foo123 I can't find simple way to do it. Need to dig into Fractal `JsonApiSerializer`.

**Comment by foo123** [comment]
Ok will do that and let you know, can you please answer my other issue here https://github.com/R3VoLuT1OneR/doctrine-rest/issues/4 about a simple example of POST data to send to the doctrine-rest to test it (NOT json data that I used). Thanks Pavel

**Comment by foo123** [comment]
I think I will need to extend `JsonApiSerializer` from `fractal` (to have a flag `includeAttributes`) and also extend `RestResponseFactory` from doctrine-rest. My test project is finished but I am thinking that maybe this can be fixed. I'll see what to do with it

**Comment by R3VoLuT1OneR** [comment]
@foo123 Please checkout new relationships actions https://github.com/R3VoLuT1OneR/doctrine-rest/tree/master/src/Doctrine/Rest/Action/Relationships.
You can find some test cases for them in unit tests.

**Comment by foo123** [comment]
@R3VoLuT1OneR  I see you have made progress maybe I will download the new source and update my test project. Thank you Pavel, when I test I will close this

**Comment by foo123** [comment]
@R3VoLuT1OneR Great work! The new related and relationships actions work great! You have refined my original ideas better. There is a `RelatedCreateAction` that is missing (I have one based on the updated doctrine-rest source code below). Maybe you can add it as well.

```php
namespace App\Action;

use League\Fractal\Resource\Item;
use Pz\Doctrine\Rest\Action\CreateAction;
use Pz\Doctrine\Rest\Contracts\RestRequestContract;
use Pz\Doctrine\Rest\RestResponse;
use Pz\Doctrine\Rest\RestRepository;

class RelatedCreateAction extends CreateAction
{
	/**
	* Field that contains the related repository
	*
	* @var RestRepository
	*/
	protected $relatedRepository;

	/**
	* Field that contains the related resourse key
	*
	* @var string
	*/
	protected $relatedKey;

    public function __construct(RestRepository $repository, RestRepository $relatedRepository, $transformer, $relatedKey)
	{
		parent::__construct($repository, $transformer);
		$this->relatedRepository = $relatedRepository;
		$this->relatedKey = $relatedKey;
	}
	
    /**
     * @param RestRequestContract $request
     *
     * @return RestResponse
     */
    public function handle($request)
    {
        $relatedEntity = $this->relatedRepository()->findById($request->getId());
		
        $headers = [];
        $class = $this->repository()->getClassName();

        $this->authorize($request, $class);
        $entity = $this->hydrateEntity($class, $request->getData());
		$setRelation = 'set' . ucfirst($this->relatedKey);
		$entity->{$setRelation}($relatedEntity);
        $this->validateEntity($entity);
        $this->repository()->getEntityManager()->persist($entity);
        $this->repository()->getEntityManager()->flush();

        if ($entity instanceof JsonApiResource) {
            $headers['Location'] = $this->repository()->linkJsonApiResource($request, $entity);
        }

        $resource = new Item($entity, $this->transformer(), $this->repository()->getResourceKey());
        return $this->response()->resource($request, $resource, RestResponse::HTTP_CREATED, $headers);
    }
	
	/**
	* @return RestRepository
	*/
	public function relatedRepository()
	{
		return $this->relatedRepository;
	}
}
```

Have tested it on my test project and everything works fine including relationships. Closing this.
